version: '3.1'
services:
  angular-ui:
    image: ionic-image:latest
    container_name: mobile-ui
    ports:
      - '8100:8100'
    volumes:
       - ./../nah-mobile:/app/mobile
    working_dir: /app/mobile
    command: ['/usr/local/bin/ionic',"serve","--no-open"]
